name: xbt370-JD
on:
  schedule:
    - cron: '4 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-xbt370-JD
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync xbt370-JD
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xbt370/JD-Auto.git"
          source_branch: "main"
          destination_branch: "xbt370-JD"
          github_token: ${{ secrets.PAT }}
